import pandas as pd
from grape import EmbeddingResult
import os
import json

embedding_cache_dir = "./cache/embeddings/"


def cache_embedding(
    embedding: EmbeddingResult,
    filename: str,
    metadata: dict = None,
):
    """
    Function developed to replace the bugged version in GRAPE for FirstOrderLINE but
    working on any embedding generated by GRAPE.
    Can optionally save additional metadata as json file.
    """
    for i in range(embedding.number_of_embeddings()):
        emb_i = embedding.get_node_embedding_from_index(i)
        emb_i.to_pickle(embedding_cache_dir + f"{filename}_{i}.pkl")
    if metadata is not None:
        with open(embedding_cache_dir + f"{filename}_metadata.json", "w") as f:
            json.dump(metadata, f)


def load_embedding(filename: str, embedding_index: int = 0):
    """
    Loads a single embedding with the specific embedding_index (the index is needed
    since GRAPE embedders can generate more than one for example with Node2Vec)
    """
    # print(embedding_cache_dir + f'{filename}_{embedding_index}.pkl')
    return pd.read_pickle(embedding_cache_dir + f"{filename}_{embedding_index}.pkl")


def load_embeddings(filename: str):
    """
    Loads all embeddings with the same name
    """
    embeddings = []
    i = 0
    while True:
        try:
            embeddings.append(load_embedding(filename, i))
            i += 1
        except FileNotFoundError:
            break
    if len(embeddings) == 0:
        raise Exception("No embeddings found")
    return embeddings


def load_or_embed(filename: str, embedding_method, graph):
    """
    If the embedding is already cached, it returns the cached version
    If the embedding is not caches, it calculates it, caches it and returns it
    """
    if is_embedding_cached(filename):
        print("Loading cached embedding")
        return load_embeddings(filename)
    else:
        print("Embedding graph")
        embedding = embedding_method.fit_transform(graph)
        print("Caching embedding")
        cache_embedding(embedding, filename)
        return embedding


def is_embedding_cached(filename: str):
    """
    Checks if the filename has an associated cached embedding
    """
    # print(embedding_cache_dir + f'{filename}_0.pkl')
    return os.path.isfile(embedding_cache_dir + f"{filename}_0.pkl")


def set_embedding_cache_dir(path: str):
    """
    Set the folder to store all the generated embeddings
    """
    global embedding_cache_dir
    embedding_cache_dir = path
